before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - darwin
      - linux
      - windows
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
